# Use an official Python runtime as the parent image
FROM python:3.9-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the docker
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the content of the application to the container
COPY .. /app/

RUN ls -al /app/

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install -r /app/tests/requirements-test.txt
