openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API for Notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /notes:
    get:
      operationId: "notes.read_all"
      tags:
        - "Notes"
      summary: "Read the list of notes"
      responses:
        "200":
          description: "Successfully read notes list"